# Generated by Django 6.0.2 on 2026-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Meno')),
                ('birth_date', models.DateField(verbose_name='Dátum narodenia')),
                ('birth_time', models.TimeField(verbose_name='Čas narodenia')),
                ('birth_place', models.CharField(max_length=200, verbose_name='Miesto narodenia')),
                ('birth_lat', models.FloatField(verbose_name='Zemepisná šírka')),
                ('birth_lon', models.FloatField(verbose_name='Zemepisná dĺžka')),
                ('timezone', models.CharField(default='Europe/Bratislava', max_length=50, verbose_name='Časové pásmo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'Natálny profil',
                'verbose_name_plural': 'Natálne profily',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransitAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_planet', models.CharField(choices=[('sun', 'Slnko'), ('moon', 'Mesiac'), ('mercury', 'Merkúr'), ('venus', 'Venuša'), ('mars', 'Mars'), ('jupiter', 'Jupiter'), ('saturn', 'Saturn'), ('uranus', 'Urán'), ('neptune', 'Neptún'), ('pluto', 'Pluto')], max_length=20, verbose_name='Tranzitná planéta')),
                ('natal_planet', models.CharField(choices=[('sun', 'Slnko'), ('moon', 'Mesiac'), ('mercury', 'Merkúr'), ('venus', 'Venuša'), ('mars', 'Mars'), ('jupiter', 'Jupiter'), ('saturn', 'Saturn'), ('uranus', 'Urán'), ('neptune', 'Neptún'), ('pluto', 'Pluto')], max_length=20, verbose_name='Natálna planéta')),
                ('aspect_type', models.CharField(choices=[('conjunction', 'Konjunkcia'), ('sextile', 'Sextil'), ('square', 'Kvadratúra'), ('trine', 'Trigón'), ('opposition', 'Opozícia')], max_length=20, verbose_name='Typ aspektu')),
                ('effect', models.CharField(choices=[('positive', 'Pozitívny'), ('negative', 'Negatívny'), ('neutral', 'Neutrálny')], default='neutral', max_length=20, verbose_name='Pôsobenie')),
                ('default_text', models.TextField(help_text='Automaticky generovaný popis tranzitu', verbose_name='Predvolený text')),
                ('user_text', models.TextField(blank=True, default='', help_text='Vlastný popis - ak je vyplnený, zobrazí sa namiesto predvoleného', verbose_name='Vlastný text')),
            ],
            options={
                'verbose_name': 'Výklad tranzitu',
                'verbose_name_plural': 'Výklady tranzitov',
                'ordering': ['transit_planet', 'natal_planet', 'aspect_type'],
                'unique_together': {('transit_planet', 'natal_planet', 'aspect_type')},
            },
        ),
    ]
