# Generated by Django 6.0.2 on 2026-02-13 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlovakCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Názov')),
                ('district', models.CharField(max_length=100, verbose_name='Okres')),
                ('lat', models.FloatField(verbose_name='Zemepisná šírka')),
                ('lon', models.FloatField(verbose_name='Zemepisná dĺžka')),
            ],
            options={
                'verbose_name': 'Slovenská obec',
                'verbose_name_plural': 'Slovenské obce',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
    ]
