# Generated by Django 6.0.2 on 2026-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0002_slovakcity_natalprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalprofile',
            name='natal_analysis_json',
            field=models.JSONField(blank=True, help_text='AI natálna analýza (sekcie)', null=True, verbose_name='Natálna analýza'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='natal_aspects_json',
            field=models.JSONField(blank=True, help_text='AI hlboká analýza natálnych aspektov', null=True, verbose_name='Analýza aspektov'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='natal_chart_json',
            field=models.JSONField(blank=True, help_text='Vypočítaný natálny horoskop (planéty, aspekty, domy)', null=True, verbose_name='Natálny chart'),
        ),
    ]
