# Generated by Django 6.0.2 on 2026-02-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0003_natalprofile_natal_analysis_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='Dátum reportu')),
                ('timezone', models.CharField(default='Europe/Bratislava', max_length=50, verbose_name='Časové pásmo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generované')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('planets_json', models.JSONField(default=list, verbose_name='Planéty')),
                ('aspects_json', models.JSONField(default=list, verbose_name='Aspekty')),
                ('ai_report_json', models.JSONField(default=dict, verbose_name='AI report')),
            ],
            options={
                'verbose_name': 'Rozbor okamihu',
                'verbose_name_plural': 'Rozbory okamihu',
                'ordering': ['-report_date'],
            },
        ),
    ]
