# Generated by Django 6.0.2 on 2026-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0004_momentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='gemini-3.1-pro-preview', max_length=100, verbose_name='Model Gemini')),
                ('api_key', models.CharField(blank=True, default='', help_text='Ak je vyplnené, má prioritu pred GEMINI_API_KEY z .env.', max_length=255, verbose_name='Gemini API key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'Gemini konfigurácia',
                'verbose_name_plural': 'Gemini konfigurácia',
            },
        ),
    ]
