# Generated by Django 6.0.2 on 2026-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0005_geminiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True, unique=True, verbose_name='Dátum')),
                ('calls_made', models.PositiveIntegerField(default=0, verbose_name='Počet volaní')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'Denné použitie Gemini',
                'verbose_name_plural': 'Denné použitie Gemini',
                'ordering': ['-usage_date'],
            },
        ),
        migrations.AddField(
            model_name='geminiconfig',
            name='max_calls_daily',
            field=models.PositiveIntegerField(default=500, help_text='Tvrdý denný limit volaní na Gemini API.', verbose_name='Max API calls denne'),
        ),
    ]
