# Generated by Django 6.0.2 on 2026-02-26 13:09

import transits.security
from django.db import migrations, models


def encrypt_existing_birth_places(apps, schema_editor):
    NatalProfile = apps.get_model('transits', 'NatalProfile')
    for profile in NatalProfile.objects.all().only('id', 'birth_place').iterator():
        raw = profile.birth_place
        if raw and not transits.security.is_encrypted(raw):
            profile.birth_place = transits.security.encrypt_text(raw)
            profile.save(update_fields=['birth_place'])


def noop_reverse(apps, schema_editor):
    # Schválne bez dešifrovania pri roll-backu.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0006_geminidailyusage_geminiconfig_max_calls_daily'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminiconfig',
            options={'verbose_name': 'AI konfigurácia', 'verbose_name_plural': 'AI konfigurácia'},
        ),
        migrations.RemoveField(
            model_name='geminiconfig',
            name='api_key',
        ),
        migrations.RenameField(
            model_name='geminiconfig',
            old_name='model_name',
            new_name='default_model',
        ),
        migrations.AlterField(
            model_name='geminiconfig',
            name='default_model',
            field=models.CharField(default='gemini-3.1-pro-preview', help_text='Príklady: gemini-3.1-pro-preview, openai:gpt-4.1-mini, openai', max_length=100, verbose_name='DEFAULT_MODEL'),
        ),
        migrations.AlterField(
            model_name='geminiconfig',
            name='max_calls_daily',
            field=models.PositiveIntegerField(default=500, help_text='Tvrdý denný limit volaní na AI API.', verbose_name='Max API calls denne'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_place',
            field=transits.security.EncryptedTextField(help_text='Šifrované uloženie citlivého údaja.', verbose_name='Miesto narodenia'),
        ),
        migrations.RunPython(encrypt_existing_birth_places, noop_reverse),
    ]
