# Generated by Django 6.0.2 on 2026-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0007_alter_geminiconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalprofile',
            name='birth_data_salt',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='User crypto salt'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='birth_date_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='Birth date (enc)'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='birth_lat_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='Birth lat (enc)'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='birth_lon_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='Birth lon (enc)'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='birth_place_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='Birth place (enc)'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='birth_time_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='Birth time (enc)'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='natal_positions_json',
            field=models.JSONField(blank=True, help_text='Predpočítané natálne pozície pre výpočet tranzitov bez potreby dešifrovania PII.', null=True, verbose_name='Natálne pozície'),
        ),
        migrations.AddField(
            model_name='natalprofile',
            name='public_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Pseudonymizovaný identifikátor pre OSS/export účely.', max_length=64, verbose_name='Public hash'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Zemepisná šírka'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Zemepisná dĺžka'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_place',
            field=models.TextField(blank=True, null=True, verbose_name='Miesto narodenia'),
        ),
        migrations.AlterField(
            model_name='natalprofile',
            name='birth_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Čas narodenia'),
        ),
    ]
