# Generated by Django 6.0.2 on 2026-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0008_natalprofile_birth_data_salt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalprofile',
            name='birth_data_recovery_encrypted',
            field=models.TextField(blank=True, default='', help_text='Server-side recovery envelope pre bezpečný re-encrypt po reset hesla.', verbose_name='Birth data recovery (enc)'),
        ),
    ]
