# Generated by Django 6.0.2 on 2026-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0009_natalprofile_birth_data_recovery_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena')], default='male', max_length=10, verbose_name='Pohlavie'),
        ),
    ]
