# Generated by Django 6.0.2 on 2026-03-03 09:00

from django.db import migrations, models


def seed_ai_model_options(apps, schema_editor):
    AIModelOption = apps.get_model('transits', 'AIModelOption')
    defaults = [
        ('GPT-5.2', 'openai:gpt-5.2', 10),
        ('Gemini Pro 2.5', 'gemini:gemini-2.5-pro', 20),
    ]
    for label, model_ref, sort_order in defaults:
        AIModelOption.objects.get_or_create(
            model_ref=model_ref,
            defaults={
                'label': label,
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0010_natalprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Viditeľný názov v UI, napr. GPT-5.2 alebo Gemini Pro 2.5.', max_length=80, verbose_name='Názov modelu')),
                ('model_ref', models.CharField(help_text='Runtime hodnota, napr. openai:gpt-5.2 alebo gemini:gemini-2.5-pro.', max_length=120, unique=True, verbose_name='Model identifikátor')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='Poradie')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Zobraziť v headri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'AI model do headeru',
                'verbose_name_plural': 'AI modely do headeru',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(seed_ai_model_options, migrations.RunPython.noop),
    ]
