# Generated by Django 6.0.2 on 2026-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0011_aimodeloption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cache key')),
                ('provider', models.CharField(default='gemini', max_length=20, verbose_name='Provider')),
                ('model_name', models.CharField(default='', max_length=120, verbose_name='Model')),
                ('response_text', models.TextField(default='', verbose_name='Response text')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Počet cache hitov')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expirácia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'AI response cache',
                'verbose_name_plural': 'AI response cache',
                'ordering': ['-updated_at'],
            },
        ),
    ]
