# Generated by Django 6.0.2 on 2026-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0012_airesponsecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='natalprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Ak je zapnuté, používateľ má Pro oprávnenia (napr. prepínanie AI modelu).', verbose_name='Pro účet'),
        ),
    ]
