# Generated by Django 6.0.2 on 2026-03-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0013_natalprofile_is_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDayReportDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='Dátum')),
                ('model_ref', models.CharField(db_index=True, max_length=120, verbose_name='Model')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Počet requestov')),
                ('cache_hits', models.PositiveIntegerField(default=0, verbose_name='Cache hity')),
                ('generated_reports', models.PositiveIntegerField(default=0, verbose_name='Nové generovania')),
                ('fallback_reports', models.PositiveIntegerField(default=0, verbose_name='Fallback odpovede')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Chyby endpointu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'AI hodnotenie dňa štatistika',
                'verbose_name_plural': 'AI hodnotenie dňa štatistiky',
                'ordering': ['-stat_date', 'model_ref'],
                'constraints': [models.UniqueConstraint(fields=('stat_date', 'model_ref'), name='uniq_ai_day_stats_date_model')],
            },
        ),
        migrations.CreateModel(
            name='AIDayReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True, verbose_name='Dátum hodnotenia')),
                ('model_ref', models.CharField(db_index=True, max_length=120, verbose_name='Model')),
                ('payload_json', models.JSONField(default=dict, verbose_name='AI payload')),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Profil updated_at snapshot')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Počet cache hitov')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generované')),
                ('last_served_at', models.DateTimeField(blank=True, null=True, verbose_name='Naposledy servované')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expirácia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_day_report_cache_rows', to='transits.natalprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'AI hodnotenie dňa cache',
                'verbose_name_plural': 'AI hodnotenie dňa cache',
                'ordering': ['-target_date', '-updated_at'],
                'indexes': [models.Index(fields=['target_date', 'model_ref'], name='transits_ai_target__859824_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'target_date', 'model_ref'), name='uniq_ai_day_cache_profile_date_model')],
            },
        ),
    ]
