# Generated by Django 6.0.2 on 2026-03-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0014_aidayreportdailystat_aidayreportcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINatalAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_ref', models.CharField(db_index=True, max_length=120, verbose_name='Model')),
                ('analysis_json', models.JSONField(default=list, verbose_name='Natálna analýza')),
                ('aspects_json', models.JSONField(default=list, verbose_name='Analýza aspektov')),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Profil updated_at snapshot')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Počet cache hitov')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generované')),
                ('last_served_at', models.DateTimeField(blank=True, null=True, verbose_name='Naposledy servované')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expirácia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_natal_analysis_cache_rows', to='transits.natalprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'AI natálna analýza cache',
                'verbose_name_plural': 'AI natálne analýzy cache',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['model_ref', 'expires_at'], name='transits_ai_model_r_cad376_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'model_ref'), name='uniq_ai_natal_cache_profile_model')],
            },
        ),
    ]
