# Generated by Django 6.0.2 on 2026-03-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_user_pro_status_from_profiles(apps, schema_editor):
    NatalProfile = apps.get_model('transits', 'NatalProfile')
    UserProStatus = apps.get_model('transits', 'UserProStatus')

    pro_by_user = {}
    for user_id, is_pro in (
        NatalProfile.objects.exclude(user_id__isnull=True).values_list('user_id', 'is_pro')
    ):
        if user_id is None:
            continue
        prev = pro_by_user.get(user_id, False)
        pro_by_user[user_id] = bool(prev or is_pro)

    if not pro_by_user:
        return

    rows = [
        UserProStatus(user_id=user_id, is_pro=is_pro)
        for user_id, is_pro in pro_by_user.items()
    ]
    UserProStatus.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0015_ainatalanalysiscache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField(default=False, help_text='Určuje, či má používateľ Pro oprávnenia (napr. prepínanie AI modelov).', verbose_name='Pro účet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pro_status', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Pro status používateľa',
                'verbose_name_plural': 'Pro statusy používateľov',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RunPython(seed_user_pro_status_from_profiles, migrations.RunPython.noop),
    ]
