# Generated by Django 6.0.2 on 2026-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0016_userprostatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodeloption',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'AI model', 'verbose_name_plural': 'AI modely'},
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='context_window',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Context window'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Popis modelu'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Pri sync z Vercel sa vypne, ak model zmizne z katalógu.', verbose_name='Dostupný v katalógu'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='is_pro_only',
            field=models.BooleanField(default=False, help_text='Ak je zapnuté, model je viditeľný a použiteľný iba pre Pro účty (alebo staff).', verbose_name='Len pre Pro účty'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Naposledy synchronizované'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='max_tokens',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max output tokens'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='model_type',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Provider/owner'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='pricing_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Pricing'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='raw_meta_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw metadata'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuálne'), ('vercel', 'Vercel AI Gateway')], db_index=True, default='manual', help_text='manual = ručne spravovaný model, vercel = synchronizovaný z Vercel AI Gateway.', max_length=20, verbose_name='Zdroj'),
        ),
        migrations.AddField(
            model_name='aimodeloption',
            name='tags_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Tagy'),
        ),
    ]
