# Generated by Django 6.0.2 on 2026-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0017_alter_aimodeloption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodeloption',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Ak je zapnuté, model je aktívny v aplikácii: zobrazí sa v header dropdown-e/compare režime a použije sa pri refresh_to_cache.', verbose_name='Aktívny'),
        ),
    ]
