# Generated by Django 6.0.2 on 2026-03-04 11:45

from django.db import migrations, models


def _normalize_model_ref(raw_model):
    value = str(raw_model or '').strip()
    if not value:
        return 'openai:gpt-5.2'

    if ':' in value:
        provider, model = value.split(':', 1)
        provider = provider.strip().lower()
        model = model.strip()
        if provider and model:
            return f"{provider}:{model}"

    if '/' in value:
        owner, model = value.split('/', 1)
        owner = owner.strip().lower()
        model = model.strip()
        if owner in ('openai',):
            return f"openai:{model}"
        if owner in ('google', 'gemini'):
            return f"gemini:{model}"
        return f"vercel:{value}"

    lower = value.lower()
    if lower.startswith('gemini'):
        return f"gemini:{value}"
    if lower.startswith(('gpt-', 'gpt4', 'gpt-4', 'gpt-5', 'o1', 'o3', 'o4')):
        return f"openai:{value}"
    return f"vercel:{value}"


def _backfill_moment_model_ref(apps, schema_editor):
    MomentReport = apps.get_model('transits', 'MomentReport')
    GeminiConfig = apps.get_model('transits', 'GeminiConfig')

    cfg = GeminiConfig.objects.order_by('-updated_at').first()
    normalized_default = _normalize_model_ref(getattr(cfg, 'default_model', '') if cfg else '')
    MomentReport.objects.filter(model_ref='').update(model_ref=normalized_default)


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0018_alter_aimodeloption_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiconfig',
            name='max_compare_models',
            field=models.PositiveSmallIntegerField(default=3, help_text='Limit modelov v compare režime (timeline + natálna analýza).', verbose_name='Max modelov v porovnaní'),
        ),
        migrations.AddField(
            model_name='momentreport',
            name='model_ref',
            field=models.CharField(db_index=True, default='', help_text='Normalizovaný model_ref (napr. openai:gpt-5.2).', max_length=120, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='momentreport',
            name='report_date',
            field=models.DateField(db_index=True, verbose_name='Dátum reportu'),
        ),
        migrations.RunPython(_backfill_moment_model_ref, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='momentreport',
            index=models.Index(fields=['report_date', 'model_ref'], name='transits_mo_report__173cd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='momentreport',
            constraint=models.UniqueConstraint(fields=('report_date', 'model_ref'), name='uniq_moment_report_date_model'),
        ),
    ]
