# Generated by Django 6.0.2 on 2026-03-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0019_geminiconfig_max_compare_models_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(choices=[('reverse', 'Reverse geocoding'), ('forward', 'Forward geocoding'), ('ip', 'IP geolocation')], db_index=True, max_length=20, verbose_name='Typ lookupu')),
                ('lookup_key', models.CharField(db_index=True, max_length=100, verbose_name='Lookup key')),
                ('cache_day', models.DateField(db_index=True, verbose_name='Cache deň')),
                ('provider', models.CharField(blank=True, default='', max_length=40, verbose_name='Provider')),
                ('payload_json', models.JSONField(default=dict, verbose_name='Payload')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Počet cache hitov')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generované')),
                ('last_served_at', models.DateTimeField(blank=True, null=True, verbose_name='Naposledy servované')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expirácia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'Location lookup cache',
                'verbose_name_plural': 'Location lookup cache',
                'ordering': ['-cache_day', '-updated_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='momentreport',
            name='uniq_moment_report_date_model',
        ),
        migrations.RemoveIndex(
            model_name='momentreport',
            name='transits_mo_report__173cd4_idx',
        ),
        migrations.AddField(
            model_name='momentreport',
            name='location_key',
            field=models.CharField(db_index=True, default='48.1486:17.1077', help_text='Normalizovaný kľúč lokality pre cache (zaokrúhlené lat/lon).', max_length=64, verbose_name='Location key'),
        ),
        migrations.AddField(
            model_name='momentreport',
            name='location_lat',
            field=models.FloatField(default=48.1486, verbose_name='Zemepisná šírka'),
        ),
        migrations.AddField(
            model_name='momentreport',
            name='location_lon',
            field=models.FloatField(default=17.1077, verbose_name='Zemepisná dĺžka'),
        ),
        migrations.AddField(
            model_name='momentreport',
            name='location_name',
            field=models.CharField(default='Bratislava, Slovensko', help_text='Textový názov lokality použitý v reporte.', max_length=160, verbose_name='Lokalita'),
        ),
        migrations.AddIndex(
            model_name='momentreport',
            index=models.Index(fields=['report_date', 'model_ref', 'location_key'], name='transits_mo_report__99d1e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='momentreport',
            constraint=models.UniqueConstraint(fields=('report_date', 'model_ref', 'location_key'), name='uniq_moment_report_date_model_location'),
        ),
        migrations.AddIndex(
            model_name='locationlookupcache',
            index=models.Index(fields=['lookup_type', 'cache_day', 'expires_at'], name='transits_lo_lookup__39918c_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationlookupcache',
            constraint=models.UniqueConstraint(fields=('lookup_type', 'lookup_key', 'cache_day'), name='uniq_location_lookup_type_key_day'),
        ),
    ]
