# Generated by Django 6.0.2 on 2026-03-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transits', '0020_locationlookupcache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprostatus',
            name='credits',
            field=models.BigIntegerField(default=0, help_text='Aktuálny kreditový zostatok pre AI volania (odpočítava sa len pri cache-miss).', verbose_name='AI kredity'),
        ),
        migrations.CreateModel(
            name='AICreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('charge', 'Odpočet'), ('topup', 'Dobitie'), ('adjustment', 'Úprava')], db_index=True, max_length=20, verbose_name='Typ transakcie')),
                ('credits_delta', models.BigIntegerField(verbose_name='Zmena kreditov')),
                ('credits_before', models.BigIntegerField(verbose_name='Stav pred')),
                ('credits_after', models.BigIntegerField(verbose_name='Stav po')),
                ('credits_requested', models.PositiveBigIntegerField(default=0, verbose_name='Požadovaný odpočet')),
                ('model_ref', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Model')),
                ('endpoint_path', models.CharField(blank=True, default='', max_length=220, verbose_name='Endpoint')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt tokeny')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Output tokeny')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total tokeny')),
                ('usage_source', models.CharField(blank=True, default='', max_length=20, verbose_name='Zdroj usage')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='Cache hit')),
                ('meta_json', models.JSONField(blank=True, default=dict, verbose_name='Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vytvorené')),
                ('pro_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='transits.userprostatus', verbose_name='Pro status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'AI kredit transakcia',
                'verbose_name_plural': 'AI kredit transakcie',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='transits_ai_user_id_9f05ca_idx'), models.Index(fields=['event_type', 'created_at'], name='transits_ai_event_t_2af9a4_idx')],
            },
        ),
    ]
